name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: baconchatwork.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker build -f ./docker/WebApp/Dockerfile -t baconchatwork.azurecr.io/baconchatportfolio:latest .
          docker push baconchatwork.azurecr.io/baconchatportfolio:latest

      # Azure Web App Deployment (Optional: if you're deploying to an Azure Web App)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name:  baconchatwork
          images:  baconchatwork.azurecr.io/baconchatportfolio:latest
