name: Build, Push Docker Image, and Redeploy with Terraform

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: baconchatwork.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker build -f ./docker/WebApp/Dockerfile -t baconchatwork.azurecr.io/baconchatportfolio:latest .
          docker push baconchatwork.azurecr.io/baconchatportfolio:latest

      # Azure Login using JSON credentials (For deploying the container instance)
      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # You can specify the version you need

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Apply the Terraform configuration
      - name: Terraform Apply
        run: terraform apply -auto-approve
